---
- hosts: master
  tasks:
  - name: create ssl dir
    file: path=/etc/kubernetes/ssl state=directory owner=root group=root
  - name: copy tsl certificates
    copy: src=gen-certs/certs/{{ item }} dest=/etc/kubernetes/ssl/{{ item }} owner=root group=root mode=0400
    with_items:
      - ca.pem
      - apiserver.pem
      - apiserver-key.pem
  - name: create flannel run dir
    file: path=/run/flannel state=directory
  - name: write flannel options
    template: src=flannel/options.env.j2 dest=/run/flannel/options.env
  - name: create flannel unit drop-in dir
    file: path=/etc/systemd/system/flanneld.service.d state=directory
  - name: write flannel etcd config drop-in
    copy: src=flannel/40-etcd-config.conf dest=/etc/systemd/system/flanneld.service.d/40-etcd-config.conf
  - name: create docker unit drop-in dir
    file: path=/etc/systemd/system/docker.service.d state=directory
  - name: write docker flannel dependency drop-in
    copy: src=flannel/40-flannel.conf dest=/etc/systemd/system/docker.service.d/40-flannel.conf
  - name: write kubelet unit file
    copy: src=kubelet/kubelet.service.master dest=/etc/systemd/system/kubelet.service
  - name: create pod manifests dir
    file: path=/etc/kubernetes/manifests state=directory
  - name: write apiserver pod manifest
    copy: src=kubelet/kube-apiserver.yaml dest=/etc/kubernetes/manifests/kube-apiserver.yaml
